version: '3.9'

services:
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./../app:/var/www

  nginx:
    image: nginx:alpine
    volumes:
      - ./../app:/var/www:rw
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      -  ${NGINX_HOST_HTTP_PORT}:80

  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

#  rabbitmq3:
#    container_name: "rabbitmq"
#    image: rabbitmq:3-management
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    ports:
#      - '5672:5672'
#      - '15672:15672'


volumes:
  db_data:
