doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            auth_user_id: 'Modules\Auth\Entity\User\IdType'
            auth_user_status: 'Modules\Auth\Entity\User\StatusType'
            auth_user_email: 'Modules\Auth\Entity\User\EmailType'
            auth_user_role: 'Modules\Auth\Entity\User\RoleType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Modules:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/modules/Auth/Entity'
                prefix: 'Modules\Auth\Entity'
                alias: Modules

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
